services:
  open-webui:
    # Using the recommended image from the official repository.
    image: ghcr.io/open-webui/open-webui:main
    container_name: proj-chat01
    restart: unless-stopped
    ports:
      # Expose the container's internal port 8080 to a configurable host port.
      - '${OPEN_WEB_UI_HTTP_PORT:-8082}:8080'
    volumes:
      # Use a Docker-managed named volume for all configuration and data.
      # This is where you will place your existing configuration.
      - open-webui-data:/app/backend/data
    environment:
      - TZ=${TZ:-UTC}
    networks:
      - open-webui_net

# Define the Docker-managed named volume.
volumes:
  open-webui-data:

networks:
  open-webui_net:
    name: ${DOCKER_NETWORK:-open-webui_network}
    driver: bridge
