# -----------------------------------------------------------------------------
# Grafana - Project-Level Data Visualization Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/proj-grafana-stack
# Purpose: Project-specific data visualization for research and microservices
# Version: Grafana 10.2.2
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

version: "3.8"

services:
  grafana:
    container_name: ${CONTAINER_NAME}
    image: grafana/grafana:${GRAFANA_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${DB_HOST}
      GF_DATABASE_PORT: ${DB_PORT}
      GF_DATABASE_USER: ${DB_USER}
      GF_DATABASE_PASSWORD: ${DB_PASS}
      GF_DATABASE_NAME: ${DB_NAME}
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASS}
    ports:
      - "${GRAFANA_HTTP_PORT}:3000"
    volumes:
      - ${VOLUME_DATA}:/var/lib/grafana
    networks:
      - grafana_network

networks:
  grafana_network:
    driver: bridge
