# -----------------------------------------------------------------------------
# Redis Docker Compose Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/redis-stack
# Purpose: High-speed caching, session storage, and lightweight message queueing
# Version: Redis 7.0
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  redis:
    container_name: ${CONTAINER_NAME}
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${VOLUME_DATA}:/data
    networks:
      - redis_network
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

networks:
  redis_network:
    driver: bridge
