# -----------------------------------------------------------------------------
# Gitea Docker Compose Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/gitea-stack
# Purpose: Lab-wide Git repository hosting for source control, GitOps, and automation
# Version: Gitea 1.21.3
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  gitea:
    container_name: ${CONTAINER_NAME}
    image: gitea/gitea:${GITEA_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ${VOLUME_DATA}:/data
    networks:
      - gitea_network

networks:
  gitea_network:
    driver: bridge
