services:
  gitea:
    # Image is now defined by an environment variable for easy version management.
    image: ${GITEA_IMAGE_VERSION:-gitea/gitea:latest}
    container_name: gitea
    restart: unless-stopped
    environment:
      # --- General & User Settings ---
      - USER_UID=${GITEA_UID:-1000}
      - USER_GID=${GITEA_GID:-1000}
      # --- Database Settings (PostgreSQL) ---
      # All database connection details are now sourced from environment variables.
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__database__SSL_MODE=${GITEA_DB_SSL_MODE:-disable}
    volumes:
      # The host path for persistent data is now defined by an environment variable.
      - ${GITEA_DATA_PATH}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # Port mappings are now defined by environment variables.
      - "${GITEA_SSH_PORT:-2222}:22"
      - "${GITEA_HTTP_PORT:-3000}:3000"
    networks:
      - gitea_net # Using a dedicated network defined below

# Define the network for this stack.
networks:
  gitea_net:
    name: ${DOCKER_NETWORK:-gitea_network}
    driver: bridge
