# -----------------------------------------------------------------------------
# GLPI Docker Compose Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/glpi-stack
# Purpose: ITIL-based service management, ticketing, and asset tracking
# Version: GLPI 10.0.10
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  glpi:
    container_name: ${CONTAINER_NAME}
    image: glpi-project/glpi:${GLPI_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      GLPI_DATABASE_TYPE: pgsql
      GLPI_DB_HOST: ${GLPI_DB_HOST}
      GLPI_DB_NAME: ${GLPI_DB_NAME}
      GLPI_DB_USER: ${GLPI_DB_USER}
      GLPI_DB_PASSWORD: ${GLPI_DB_PASSWORD}
    ports:
      - "${GLPI_HTTP_PORT}:80"
    volumes:
      - ${VOLUME_DATA}:/var/www/html/glpi
    networks:
      - glpi_network

networks:
  glpi_network:
    driver: bridge
