# -----------------------------------------------------------------------------
# Zitadel - Identity & Access Management (IAM) Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/zitadel-stack
# Purpose: SSO bridge for Entra ID, authentication proxy, and identity provider
# Version: Zitadel 2.41.1
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  zitadel:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      ZITADEL_DATABASE_TYPE: postgres
      ZITADEL_DATABASE_POSTGRES_HOST: ${DB_HOST}
      ZITADEL_DATABASE_POSTGRES_PORT: ${DB_PORT}
      ZITADEL_DATABASE_POSTGRES_USER: ${DB_USER}
      ZITADEL_DATABASE_POSTGRES_PASSWORD: ${DB_PASS}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${DB_NAME}
      ZITADEL_EXTERNALDOMAIN: ${EXTERNAL_DOMAIN}
      ZITADEL_TLS_ENABLED: "false"
      ZITADEL_LOG_LEVEL: "info"
    ports:
      - "${ZITADEL_HTTP_PORT}:8080"
      - "${ZITADEL_ADMIN_PORT}:8081"
    volumes:
      - ${VOLUME_DATA}:/zitadel/data
    networks:
      - zitadel_network

networks:
  zitadel_network:
    driver: bridge
