# =============================================================================
# PROXMOX ASTRONOMY LAB - ANSIBLE CONFIGURATION
# =============================================================================
# Purpose: 
# Scope: 7-node Proxmox cluster with 20+ VMs running Ubuntu 24.04 Server
# Architecture: Hybrid Kubernetes + VM infrastructure with centralized management
# Agent Integration: Designed for MCP-based AI agent orchestration
#
# Network: Dual-VLAN (10.25.10.x mgmt, 10.25.20.x project)
# Control Node: mgmt-ansible01 (10.25.10.7)
# Target Infrastructure: Linux VMs across radioastronomy.io domain
#
# Last Updated: July 23, 2025
# =============================================================================
# roles/monitoring/tasks/main.yml
---
- name: Update Prometheus configuration for current infrastructure
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    backup: yes
  when: inventory_hostname == "proj-mon01"
  notify: restart prometheus

- name: Ensure node-exporter is configured properly
  include_tasks: node-exporter.yml
  tags: node-exporter

