# -----------------------------------------------------------------------------
# Gitea - Project-Specific Source Control Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/proj-gitea-stack
# Purpose: Project-specific Git repository management for research & development
# Version: Gitea 1.21.3
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  gitea:
    container_name: ${CONTAINER_NAME}
    image: gitea/gitea:${GITEA_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ${VOLUME_DATA}:/data
    networks:
      - gitea_network

networks:
  gitea_network:
    driver: bridge
