# -----------------------------------------------------------------------------
# MariaDB Docker Compose Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/mariadb-stack
# Purpose: Database solution for applications incompatible with PostgreSQL
# Version: MariaDB 10.6
# Notes: Utilizes external .env file for configurations
# -----------------------------------------------------------------------------

services:
  mariadb:
    container_name: ${CONTAINER_NAME}
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${VOLUME_DATA}:/var/lib/mysql
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
