# Neo4j Graph Database Platform - Docker Compose Configuration
# Optimized for VM 2018: 8 vCPU, 24GB RAM, Ubuntu 24.04 CIS L2
# Documentation: See README.md for complete setup and configuration

version: '3.8'

services:
  neo4j:
    image: ${NEO4J_IMAGE_VERSION:-neo4j:5.26.9}
    container_name: ${NEO4J_CONTAINER_NAME:-neo4j01}
    
    environment:
      # Authentication
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/Defeat-Shell-Loyalty-Pardon-Commercial-0}

      # Memory configuration optimized for 24GB VM
      - NEO4J_server_memory_heap_initial__size=${NEO4J_HEAP_INITIAL_SIZE:-4G}
      - NEO4J_server_memory_heap_max__size=${NEO4J_HEAP_MAX_SIZE:-8G}
      - NEO4J_server_memory_pagecache_size=${NEO4J_PAGECACHE_SIZE:-12G}

      # Network configuration
      - NEO4J_server_default__listen__address=${NEO4J_LISTEN_ADDRESS:-0.0.0.0}

      # Plugins
      - NEO4J_PLUGINS=${NEO4J_PLUGINS:-["apoc"]}

      # Configuration
      - NEO4J_server_config_strict__validation_enabled=${NEO4J_STRICT_VALIDATION:-false}
      
      # Timezone
      - TZ=${TZ:-UTC}

    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"  # Neo4j Browser
      - "${NEO4J_BOLT_PORT:-7687}:7687"  # Bolt protocol

    volumes:
      - ${NEO4J_DATA_PATH:-./data}:/data
      - ${NEO4J_LOGS_PATH:-./logs}:/logs
      - ${NEO4J_PLUGINS_PATH:-./plugins}:/plugins
      - ${NEO4J_IMPORT_PATH:-./import}:/var/lib/neo4j/import

    restart: ${RESTART_POLICY:-unless-stopped}

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Security context (basic container security)
    security_opt:
      - no-new-privileges:true

    # Resource limits for VM 2018 (8 vCPU, 24GB RAM)
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 20G
        reservations:
          cpus: '4.0'
          memory: 16G

    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 3

# ==============================================================================
# CONFIGURATION NOTES
# ==============================================================================
# 
# SECURITY STATUS:
# - Host: Ubuntu 24.04 CIS L2 hardened + Wazuh monitoring ✅
# - Container: Basic security, hardening pending 🔄
# - Application: Default auth, enterprise controls pending 🔄
# - Network: Basic isolation, advanced segmentation pending 🔄
# - Encryption: Not implemented ❌
#
# PERFORMANCE OPTIMIZATION:
# - Memory: 8GB heap + 12GB page cache for 24GB VM
# - CPU: 8 core limit matching VM specs
# - Storage: Host volumes for persistence
#
# FUTURE ENHANCEMENTS:
# - SSL/TLS encryption
# - LDAP/SSO integration  
# - Enhanced monitoring
# - Backup automation
# - Network security policies
#
# ==============================================================================