# -----------------------------------------------------------------------------
# Nextcloud - Secure On-Prem Research Collaboration Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/proj-nextcloud-stack
# Purpose: On-prem collaboration platform for research, backed by NFS & Windows shares
# Version: Nextcloud 27.1.2
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

version: "3.8"

services:
  nextcloud:
    container_name: ${CONTAINER_NAME}
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_DOMAIN}
    ports:
      - "${NEXTCLOUD_HTTP_PORT}:80"
    volumes:
      - ${VOLUME_DATA}:/var/www/html
      - ${NFS_MOUNT}:/mnt/nfs
      - ${WINDOWS_SHARE}:/mnt/windows
    networks:
      - nextcloud_network

  onlyoffice:
    container_name: ${ONLYOFFICE_CONTAINER}
    image: onlyoffice/documentserver:${ONLYOFFICE_VERSION}
    restart: unless-stopped
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
    ports:
      - "${ONLYOFFICE_HTTP_PORT}:80"
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
