# =============================================================================
# PROXMOX ASTRONOMY LAB - ANSIBLE CONFIGURATION
# =============================================================================
# Purpose: 
# Scope: 7-node Proxmox cluster with 20+ VMs running Ubuntu 24.04 Server
# Architecture: Hybrid Kubernetes + VM infrastructure with centralized management
# Agent Integration: Designed for MCP-based AI agent orchestration
#
# Network: Dual-VLAN (10.25.10.x mgmt, 10.25.20.x project)
# Control Node: mgmt-ansible01 (10.25.10.7)
# Target Infrastructure: Linux VMs across radioastronomy.io domain
#
# Last Updated: July 23, 2025
# =============================================================================
# roles/baseline/tasks/system-hardening.yml
---
- name: Ensure SSH is properly configured (basic hardening)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes
  notify: restart ssh

- name: Disable unused services (if present)
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - bluetooth
    - cups
  ignore_errors: yes

