services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${NPM_HTTP_PORT:-80}:80'       # Public HTTP Port
      - '${NPM_HTTPS_PORT:-443}:443'    # Public HTTPS Port
      - '${NPM_ADMIN_PORT:-81}:81'      # Admin Web Port
    environment:
      # This disables IPv6 support within the container.
      - DISABLE_IPV6=true
      # Optional: Define the SQLite DB file location within the container.
      # Default is /data/database.sqlite, which is usually fine.
      # - DB_SQLITE_FILE="/data/database.sqlite"
    volumes:
      # All NPM data is stored under a single, configurable host path.
      - '${NPM_DATA_PATH}/data:/data'
      - '${NPM_DATA_PATH}/letsencrypt:/etc/letsencrypt'
    networks:
      - npm_net

networks:
  npm_net:
    name: ${DOCKER_NETWORK:-npm_network}
    driver: bridge
