# -----------------------------------------------------------------------------
# RabbitMQ Docker Compose Stack
# Maintained by: Don (GitHub: https://github.com/vintagedon)
# Repository: https://gitea.beardinthe.cloud/Portainer_Stacks/rabbitmq-stack
# Purpose: Message broker for JSON file transfers, telemetry data, and lab communication
# Version: RabbitMQ 3.12-management
# Notes: Uses external stack.env file for configurations
# -----------------------------------------------------------------------------

services:
  rabbitmq:
    container_name: ${CONTAINER_NAME}
    image: rabbitmq:${RABBITMQ_VERSION}-management
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - ${VOLUME_DATA}:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
