global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
# ============================
# PROMETHEUS SERVER METRICS
# ============================
- job_name: "prometheus"
  static_configs:
  - targets:
    - localhost:9090
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "localhost:9090"
    replacement: "prometheus-metrics"
    target_label: instance

# ============================
# LOKI SERVER METRICS
# ============================
- job_name: "loki"
  static_configs:
  - targets:
    - localhost:3100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "localhost:3100"
    replacement: "loki-metrics"
    target_label: instance

# ============================
# INFLUXDB SERVER METRICS
# ============================
- job_name: "influxdb"
  static_configs:
  - targets:
    - localhost:8086
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "localhost:8086"
    replacement: "influxdb-metrics"
    target_label: instance

# ============================
# PROXMOX NODES - NODE EXPORTER
# ============================
- job_name: "proxmox_nodes"
  static_configs:
  - targets:
    - 10.16.207.201:9100
    - 10.16.207.202:9100
    - 10.16.207.203:9100
    - 10.16.207.204:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.16.207.201:9100"
    replacement: "proxmox-node01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.16.207.202:9100"
    replacement: "proxmox-node02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.16.207.203:9100"
    replacement: "proxmox-node03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.16.207.204:9100"
    replacement: "proxmox-node04"
    target_label: instance

# ============================
# ALL SERVERS GROUP
# ============================
- job_name: "all"
  static_configs:
  - targets:
    # Linux Servers
    - 10.25.20.4:9100
    - 10.25.20.5:9100
    - 10.25.20.6:9100
    - 10.25.20.7:9100
    - 10.25.20.8:9100
    - 10.25.20.9:9100
    - 10.25.20.10:9100
    - 10.25.20.11:9100 # Not online yet
    - 10.25.20.12:9100 # Not online yet
    - 10.25.10.3:9100
    - 10.25.20.3:9100
    - locahost:9100
    - 10.25.10.14:9100
    - 10.25.10.15:9100
    - 10.25.10.16:9100
    - 10.25.20.13:9100
    - 10.25.20.14:9100
    - 10.25.20.15:9100
    - 10.25.20.21:9100
    - 10.25.10.17:9100
    - 10.25.10.18:9100
    # Windows Servers
    - 10.25.10.2:9182
    - 10.25.20.2:9182
    - 10.25.20.19:9182
    - 10.25.20.20:9182
  relabel_configs:
  # Linux Hosts
  - source_labels: [ __address__ ]
    regex: "10.25.20.4:9100"
    replacement: "proj-k8sm01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.5:9100"
    replacement: "proj-k8sm02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.6:9100"
    replacement: "proj-k8sm03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.7:9100"
    replacement: "proj-k8sw01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.8:9100"
    replacement: "proj-k8sw02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.9:9100"
    replacement: "proj-k8sw03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.10:9100"
    replacement: "proj-k8sw04"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.3:9100"
    replacement: "lab-dns01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.3:9100"
    replacement: "lab-dns02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.13:9100"
    replacement: "lab-mon01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.13:9100"
    replacement: "proj-pgts01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.14:9100"
    replacement: "proj-pg01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.15:9100"
    replacement: "proj-pggis01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.21:9100"
    replacement: "proj-apps01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.17:9100"
    replacement: "lab-db01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.18:9100"
    replacement: "lab-apps01"
    target_label: instance
  # Windows Hosts
  - source_labels: [ __address__ ]
    regex: "10.25.10.2:9182"
    replacement: "dc01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.2:9182"
    replacement: "dc02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.19:9182"
    replacement: "proj-fs01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.20:9182"
    replacement: "proj-rds01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.14:9100"
    replacement: "lab-soc1"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.15:9100"
    replacement: "lab-ansible01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.16:9100"
    replacement: "lab-port01"
    target_label: instance

# ============================
# LINUX SERVERS GROUP (WITH RELABELS)
# ============================
- job_name: "linux"
  static_configs:
  - targets:
    - 10.25.20.4:9100
    - 10.25.20.5:9100
    - 10.25.20.6:9100
    - 10.25.20.7:9100
    - 10.25.20.8:9100
    - 10.25.20.9:9100
    - 10.25.20.10:9100
    - 10.25.20.11:9100 # Not online yet
    - 10.25.20.12:9100 # Not online yet
    - 10.25.10.3:9100
    - 10.25.20.3:9100
    - 10.25.10.13:9100
    - 10.25.10.14:9100
    - 10.25.10.15:9100
    - 10.25.10.16:9100
    - 10.25.20.13:9100
    - 10.25.20.14:9100
    - 10.25.20.15:9100
    - 10.25.20.21:9100
    - 10.25.10.17:9100
    - 10.25.10.18:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.4:9100"
    replacement: "proj-k8sm01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.5:9100"
    replacement: "proj-k8sm02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.6:9100"
    replacement: "proj-k8sm03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.7:9100"
    replacement: "proj-k8sw01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.8:9100"
    replacement: "proj-k8sw02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.9:9100"
    replacement: "proj-k8sw03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.10:9100"
    replacement: "proj-k8sw04"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.3:9100"
    replacement: "lab-dns01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.3:9100"
    replacement: "lab-dns02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.13:9100"
    replacement: "lab-mon01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.13:9100"
    replacement: "proj-pgts01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.14:9100"
    replacement: "proj-pg01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.15:9100"
    replacement: "proj-pggis01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.21:9100"
    replacement: "proj-apps01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.17:9100"
    replacement: "lab-db01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.18:9100"
    replacement: "lab-apps01"
    target_label: instance

# ============================
# WINDOWS SERVERS GROUP (WITH RELABELS)
# ============================
- job_name: "windows"
  static_configs:
  - targets:
    - 10.25.10.2:9182
    - 10.25.20.2:9182
    - 10.25.20.19:9182
    - 10.25.20.20:9182
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.10.2:9182"
    replacement: "dc01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.2:9182"
    replacement: "dc02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.19:9182"
    replacement: "proj-fs01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.20:9182"
    replacement: "proj-rds01"
    target_label: instance

# ============================
# KUBERNETES CONTROL PLANE
# ============================
- job_name: "k8s_masters"
  static_configs:
  - targets:
    - 10.25.20.4:9100
    - 10.25.20.5:9100
    - 10.25.20.6:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.4:9100"
    replacement: "proj-k8sm01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.5:9100"
    replacement: "proj-k8sm02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.6:9100"
    replacement: "proj-k8sm03"
    target_label: instance

# ============================
# KUBERNETES WORKER NODES
# ============================
- job_name: "k8s_workers"
  static_configs:
  - targets:
    - 10.25.20.7:9100
    - 10.25.20.8:9100
    - 10.25.20.9:9100
    - 10.25.20.10:9100
    - 10.25.20.11:9100
    - 10.25.20.12:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.7:9100"
    replacement: "proj-k8sw01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.8:9100"
    replacement: "proj-k8sw02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.9:9100"
    replacement: "proj-k8sw03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.10:9100"
    replacement: "proj-k8sw04"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.11:9100"
    replacement: "proj-k8sw05"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.12:9100"
    replacement: "proj-kasm01"
    target_label: instance

# ============================
# DATABASE SERVERS GROUP
# ============================
- job_name: "databases"
  static_configs:
  - targets:
    - 10.25.20.13:9100
    - 10.25.20.14:9100
    - 10.25.20.15:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.13:9100"
    replacement: "proj-pgts01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.14:9100"
    replacement: "proj-pg01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.15:9100"
    replacement: "proj-pggis01"
    target_label: instance

# ============================
# POSTGRES EXPORTER GROUP
# ============================
- job_name: 'postgres_exporter'
  static_configs:
  - targets:
    - '10.25.20.13:9187' # proj-pgts01
    - '10.25.20.14:9187' # proj-pg01
    - '10.25.20.15:9187' # proj-pggis01
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: instance
    replacement: "proj-pgts01"
    regex: "10.25.20.13:9187"
  - source_labels: [ __address__ ]
    target_label: instance
    replacement: "proj-pg01"
    regex: "10.25.20.14:9187"
  - source_labels: [ __address__ ]
    target_label: instance
    replacement: "proj-pggis01"
    regex: "10.25.20.15:9187"

# ============================
# APPLICATION SERVERS GROUP
# ============================
- job_name: "app_servers"
  static_configs:
  - targets:
    - 10.25.20.21:9100
    - 10.25.10.17:9100
    - 10.25.10.18:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.21:9100"
    replacement: "proj-apps01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.17:9100"
    replacement: "lab-db01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.18:9100"
    replacement: "lab-apps01"
    target_label: instance

# ============================
# DOMAIN CONTROLLERS
# ============================
- job_name: "dom_controllers"
  static_configs:
  - targets:
    - 10.25.10.2:9182
    - 10.25.20.2:9182
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.10.2:9182"
    replacement: "dc01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.2:9182"
    replacement: "dc02"
    target_label: instance

# ============================
# FILE SERVERS
# ============================
- job_name: "file_servers"
  static_configs:
  - targets:
    - 10.25.20.19:9182
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.19:9182"
    replacement: "proj-fs01"
    target_label: instance

# ============================
# PROCESS EXPORTER (ONLY FOR LINUX SERVERS)
# ============================
- job_name: "process_exporter"
  static_configs:
  - targets:
    - 10.25.20.4:9256
    - 10.25.20.5:9256
    - 10.25.20.6:9256
    - 10.25.20.7:9256
    - 10.25.20.8:9256
    - 10.25.20.9:9256
    - 10.25.20.10:9256
    - 10.25.20.11:9256
    - 10.25.20.12:9256
    - 10.25.10.3:9256
    - 10.25.20.3:9256
    - 10.25.10.13:9256
    - 10.25.10.14:9256
    - 10.25.10.15:9256
    - 10.25.10.16:9256
    - 10.25.20.13:9256
    - 10.25.20.14:9256
    - 10.25.20.15:9256
    - 10.25.20.21:9256
    - 10.25.10.17:9256
    - 10.25.10.18:9256
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.4:9256"
    replacement: "proj-k8sm01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.5:9256"
    replacement: "proj-k8sm02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.6:9256"
    replacement: "proj-k8sm03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.7:9256"
    replacement: "proj-k8sw01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.8:9256"
    replacement: "proj-k8sw02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.9:9256"
    replacement: "proj-k8sw03"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.10:9256"
    replacement: "proj-k8sw04"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.3:9256"
    replacement: "lab-dns01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.3:9256"
    replacement: "lab-dns02"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.13:9256"
    replacement: "lab-mon01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.13:9256"
    replacement: "proj-pgts01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.14:9256"
    replacement: "proj-pg01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.15:9256"
    replacement: "proj-pggis01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.21:9256"
    replacement: "proj-apps01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.17:9256"
    replacement: "lab-db01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.10.18:9256"
    replacement: "lab-apps01"
    target_label: instance

# ============================
# MONITORING INFRASTRUCTURE
# ============================
- job_name: "monitoring"
  static_configs:
  - targets:
    - localhost:9100
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "localhost:9100"
    replacement: "lab-mon01"
    target_label: instance

# ============================
# SWITCH SNMP EXPORTER MONITORING
# ============================
- job_name: 'snmp'
  static_configs:
  - targets:
    - 10.16.207.200 # labswitch01
    - 10.16.207.207 # labswitch02
  metrics_path: /snmp
  params:
    module: [ if_mib ]
    auth: [ public_v2 ] # SNMPv2c with 'public' community
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: __param_target
  - source_labels: [ __param_target ]
    target_label: instance
  - target_label: __address__
    replacement: 127.0.0.1:9116 # Redirects requests to `snmp_exporter` on mon01

# ============================
# NVIDIA GPU EXPORTER
# ============================
- job_name: "gpu"
  static_configs:
  - targets:
    - 10.25.20.10:9835
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.20.10:9835"
    replacement: "k8sw04"
    target_label: instance

# ============================
# PI-HOLE EXPORTERS
# ============================
- job_name: "pihole"
  static_configs:
  - targets:
    - 10.25.10.3:9617 # lab-dns01
    - 10.25.20.3:9617 # dns02
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.10.3:9617"
    replacement: "lab-dns01"
    target_label: instance
  - source_labels: [ __address__ ]
    regex: "10.25.20.3:9617"
    replacement: "dns02"
    target_label: instance

# ============================
# GITEA01 REPOSITORY METRICS
# ============================
- job_name: "gitea"
  metrics_path: "/metrics"
  static_configs:
  - targets: [ "10.25.10.18:3000" ]
  relabel_configs:
  - source_labels: [ __address__ ]
    regex: "10.25.10.18:3000"
    replacement: "lab-gitea01"
    target_label: instance

# ============================
# CADVISOR DOCKER METRICS
# ============================
- job_name: "cadvisor_nodes"
  metrics_path: "/metrics"
  scheme: http
  static_configs:
  - targets:
    - "10.25.10.18:8080" # lab-apps01
    - "10.25.20.21:8080" # proj-apps01
    - "10.25.10.17:8080" # lab-db01
    labels:
      env: "lab"
      role: "cadvisor"
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: instance
    regex: "10.25.10.18:8080"
    replacement: "lab-apps01"
  - source_labels: [ __address__ ]
    target_label: instance
    regex: "10.25.20.21:8080"
    replacement: "proj-apps01"
  - source_labels: [ __address__ ]
    target_label: instance
    regex: "10.25.10.17:8080"
    replacement: "lab-db01"

# Global SNMP Exporter metrics
- job_name: 'snmp_exporter'
  static_configs:
  - targets: [ '127.0.0.1:9116' ]

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "localhost:9093"

rule_files:
- "alert.rules.yml"
